module.exports = {
  // Global App actions
  INIT_SESSION: 'INIT_SESSION',
  FINISH_INIT_APP: 'FINISH_INIT_APP',
  SET_GENERAL_ERROR: 'SET_GENERAL_ERROR',
  CLEAR_GENERAL_ERROR: 'CLEAR_GENERAL_ERROR',
  START_APP_LOADING: 'START_APP_LOADING',
  STOP_APP_LOADING: 'STOP_APP_LOADING',
  CHANGE_GENERAL_CONFIRM_DIALOG: 'CHANGE_GENERAL_CONFIRM_DIALOG',

  // Init App data
  GET_META_DATA: 'GET_META_DATA',
  RECEIVE_MENU: 'RECEIVE_MENU',
  CHANGE_STATE_POPUP: 'CHANGE_STATE_POPUP',

  // Generic actions
  OPEN_DIALOG_GENERIC: 'OPEN_DIALOG_GENERIC',
  CLOSE_DIALOG_GENERIC: 'CLOSE_DIALOG_GENERIC',
  CHANGE_TABLE_PAGE_SIZE: 'CHANGE_TABLE_PAGE_SIZE',
  CHANGE_TABLE_ACTIVE_PAGE: 'CHANGE_TABLE_ACTIVE_PAGE',
  SELECT_TABLE_ITEM: 'SELECT_TABLE_ITEM',
  CHANGE_FILTER_GENERIC: 'CHANGE_FILTER_GENERIC',

  // Login
  REQUEST_LOGIN: 'REQUEST_LOGIN',
  LOGIN_SUCCESSFULLY: 'LOGIN_SUCCESSFULLY',
  GET_PROFILE_SUCCESSFULLY: 'GET_PROFILE_SUCCESSFULLY',
  GET_PROFILE_ERROR: 'GET_PROFILE_ERROR',
  CONFIRM_PASSWORD_ERROR: 'CONFIRM_PASSWORD_ERROR',
  CONFIRM_PASSWORD_SUCCESSFULLY: 'CONFIRM_PASSWORD_SUCCESSFULLY',
  CONFIRM_PASSWORD_CLEAR: 'CONFIRM_PASSWORD_CLEAR',
  SET_AUTHENTICATION: 'SET_AUTHENTICATION',
  RESET_AUTHENTICATION: 'RESET_AUTHENTICATION',
  SET_PROFILE: 'SET_PROFILE',
  EXCHANGE_ACCESS_TOKEN: 'EXCHANGE_ACCESS_TOKEN',

  // Setting
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  RECEIVE_SETTING: 'RECEIVE_SETTING',

  // Order
  RECEIVE_LIST_ORDER_MANAGEMENT_INFOS: 'RECEIVE_LIST_ORDER_MANAGEMENT_INFOS',
  RECEIVE_ORDER_DETAIL: 'RECEIVE_ORDER_DETAIL',
  CHANGE_FILTER_ORDER_MANAGEMENT: 'CHANGE_FILTER_ORDER_MANAGEMENT',

  // Report Restaurant
  RECEIVE_LIST_REPORT_RESTAURANT: 'RECEIVE_LIST_REPORT_RESTAURANT',
  CHANGE_FILTER_REPORT_RESTAURANT: 'CHANGE_FILTER_REPORT_RESTAURANT',

  // Category
  RECEIVE_CATEGORY: 'RECEIVE_CATEGORY',

  // Cart
  ORDER_ADD_TO_CART: 'ORDER_ADD_TO_CART',
  ORDER_REMOVE_ITEM_CART: 'ORDER_REMOVE_ITEM_CART',
  ORDER_CHANGE_QUALITY_CART: 'ORDER_CHANGE_QUALITY_CART',
  ORDER_SAVE_CART: 'ORDER_SAVE_CART'
};
